language: csharp

matrix:
    include:
        - dotnet: 3.1
          mono: latest

solution: xunit.testlogger.sln

script:
    - dotnet pack
    - dotnet test test/Xunit.Xml.TestLogger.AcceptanceTests/Xunit.Xml.TestLogger.AcceptanceTests.csproj
